window.SucessoUITranslations = {
  es: {
    nav_collections: 'COLECCIONES',
    nav_shop: 'SHOP',
    about_manifesto_heading: 'EL SUCESSO ES HACERLO A TU MANERA.',
    about_manifesto_1: 'Sucesso empieza con una idea: crear la ropa que queremos llevar. Gráficos propios, siluetas amplias y espacio para expresarnos sin pedir permiso.',
    about_manifesto_2: 'Nos mueve lo que todavía está por hacer. Probar una idea, cambiarla y volver a intentarlo. Cada diseño es parte de ese proceso. La marca está tomando forma, y queremos que tenga una voz que se reconozca como nuestra.',
    about_manifesto_3: 'Para quienes encuentran su propio camino. Para quienes crean, se equivocan y siguen. Sucesso es lo que decides construir.',
    reset_title: 'Recuperar contraseña',
    reset_email: 'Correo electrónico',
    reset_submit: 'Enviar correo de recuperación',
    reset_back: 'Volver a iniciar sesión',
    reset_wait: 'Enviando…',
    reset_success: 'Si existe una cuenta con este correo, recibirás un enlace para restablecer la contraseña. Revisa también la carpeta de spam.',
    reset_invalid: 'Introduce un correo electrónico válido.',
    reset_network: 'No se pudo conectar. Comprueba tu conexión e inténtalo de nuevo.',
    reset_limit: 'Demasiados intentos. Espera unos minutos antes de volver a probar.',
    reset_error: 'No se pudo enviar el enlace. Inténtalo nuevamente.',
    search_more_results: 'VER TODOS LOS RESULTADOS',
    search_empty: 'No se encontraron productos. Prueba con otra búsqueda.',
    search_start: 'Escribe lo que quieres buscar.',
    search_loading: 'Cargando resultados…',
    search_failure: 'No se pudo cargar el catálogo.',
    search_retry: 'Reintentar',
    search_count_template: '{count} resultados para "{query}"',
    search_one_template: '1 resultado para "{query}"'
  },
  en: {
    nav_collections: 'COLLECTIONS',
    nav_shop: 'SHOP',
    about_manifesto_heading: 'SUCESSO IS MAKING IT YOUR OWN.',
    about_manifesto_1: 'Sucesso starts with an idea: to create the clothes we want to wear. Original graphics, relaxed silhouettes and room to express ourselves without asking permission.',
    about_manifesto_2: 'We are driven by what is still ahead. Trying an idea, changing it and trying again. Every design is part of that process. The brand is taking shape, and we want its voice to be unmistakably ours.',
    about_manifesto_3: 'For those who find their own way. For those who create, get it wrong and keep going. Sucesso is what you choose to build.',
    reset_title: 'Reset your password',
    reset_email: 'Email',
    reset_submit: 'Send reset email',
    reset_back: 'Back to login',
    reset_wait: 'Sending…',
    reset_success: 'If an account exists for this email, you will receive a password reset link. Please also check your spam folder.',
    reset_invalid: 'Enter a valid email address.',
    reset_network: 'Could not connect. Check your connection and try again.',
    reset_limit: 'Too many attempts. Wait a few minutes before trying again.',
    reset_error: 'The link could not be sent. Please try again.',
    search_more_results: 'SEE ALL RESULTS',
    search_empty: 'No products found. Try another search.',
    search_start: 'Enter what you would like to search for.',
    search_loading: 'Loading results…',
    search_failure: 'The catalog could not be loaded.',
    search_retry: 'Try again',
    search_count_template: '{count} results for "{query}"',
    search_one_template: '1 result for "{query}"'
  }
};
